package mapreduce

import (
	"unicode"
	"strconv"
	"strings"
)

// The mapping function is called once for each piece of the input.
// In this framework, the value is the contents of the file being
// processed. The return value should be a slice of key/value pairs,
// each represented by a mapreduce.KeyValue.
// A COMPLETER
func MapWordCount(value string) (res []KeyValue) {

}

// The reduce function is called once for each key generated by Map,
// with a list of that key's string value (merged across all
// inputs). The return value should be a single output value for that
// key.
// A COMPLETER
func ReduceWordCount(key string, values []string) string {

}
